# Generated by Django 6.0.7 on 2026-07-22 09:09

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_enable_btree_gist'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['requested', 'confirmed'])), expressions=[('service', '='), (models.Func('start_time', 'end_time', function='tstzrange'), '&&')], name='exclude_overlapping_bookings'),
        ),
    ]
